control_panel/urls.py
from django.conf.urls import url
from newsletters.views import control_newsletter, control_newsletter_list, control_newsletter_detail, control_newsletter_edit, control_newsletter_delete

urlpatterns = [
    url(r'^newsletter/$', control_newsletter, name='control_newsletter'),
    url(r'^newsletter-list/$', control_newsletter_list, name='control_newsletter_list'),
    url(r'^newsletter-detail/(?P<pk>\d+)/$', control_newsletter_detail, name='control_newsletter_detail'),
    url(r'^newsletter-edit/(?P<pk>\d+)/$', control_newsletter_edit, name='control_newsletter_edit'),
    url(r'^newsletter-delete/(?P<pk>\d+)/$', control_newsletter_delete, name='control_newsletter_delete'),
]

master/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^control/', include('control_panel.urls',  namespace='control_panel', app_name='control_panel')),
    url(r'^newsletter/', include('newsletters.urls',  namespace='newsletters', app_name='newsletters')),
    url(r'^tutorials/', include('tutorials.urls',  namespace='tutorials', app_name='tutorials')),
    url(r'^accounts/', include('accounts.urls',  namespace='accounts', app_name='accounts')),
]

control_panel/models.py
from django.db import models

# Create your models here.

templates/control_panel/control_newsletter.html
{% extends "control_base.html" %}

{% load crispy_forms_tags %}

{% block content %}
	<h1 class="page-header">Dashboard</h1>  
	<form method="POST">{% csrf_token %}
		<div class="input-group">
			{{form|crispy}}
			<span class="input-group-btn">
				<button class="btn btn-default" type="submit">Save</button>
			</span>
		</div>
	</form>    
{% endblock %}

templates/control_panel/control_newsletter_delete.html
{% extends "control_base.html" %}

{% load crispy_forms_tags %}

{% block content %}
	<h1 class="page-header">Dashboard</h1>  
	<form method="POST">{% csrf_token %}
		<div class="input-group">
			{{form|crispy}}
			<span class="input-group-btn">
				<button class="btn btn-danger" type="submit">Delete</button>
			</span>
		</div>
	</form>    
{% endblock %}

templates/control_panel/control_newsletter_detail.html
{% extends "control_base.html" %}

{% block content %}
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<div class="page-header">
		<h1>{{newsletter.subject}}</h1>
	</div>
	{{newsletter.body}}
	<div class="col-sm-8 col-sm-offset-4">
		<div class="col-sm-2"><a href="{% url 'control_panel:control_newsletter_edit' pk=newsletter.pk %}"><button>Edit</button></a></div>
		<div class="col-sm-2"><a href="{% url 'control_panel:control_newsletter_delete' pk=newsletter.pk %}"><button>Delete</button></a></div>
		<div class="col-sm-2"><a href="{% url 'control_panel:control_newsletter' %}"><button class="btn btn-success">New</button></a></div>
	</div>
</div> 
{% endblock %}	

templates/control_panel/control_newsletter_list.html
{% extends "control_base.html" %}

{% block content %}
	<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
		<div class="row">
			<div class="col-sm-10">
				<h1 class="page-header">All Newsletters</h1>
			</div>
			<div class="col-sm-2">
				<a href="{% url 'control_panel:control_newsletter' %}"><button type="button" class="btn btn-success">New Newsletter</button></a>
			</div>
		</div>
		<div class="table-responsive table-hover">
			<table class="table">
				<thead>
					<th>Subject</th>
					<th>Status</th>
					<th>Created</th>
					<th>Updated</th>
					<th>Edit</th>
					<th>Delete</th>
				</thead>
				<tbody>
					{% for item in items %}
						<tr>
							<td><a href="{% url 'control_panel:control_newsletter_detail' pk=item.pk %}">{{ item.subject }}</a></td>
							<td>{{ item.status }}</td>
							<td>{{ item.created }}</td>
							<td>{{ item.updated }}</td>
							<td><a href="{% url 'control_panel:control_newsletter_edit' pk=item.pk %}">Edit</a></td>
							<td><a href="{% url 'control_panel:control_newsletter_delete' pk=item.pk %}">Delete</a></td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		{% include "pagination.html" %}
	</div>  
{% endblock %}