master/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^control/', include('control_panel.urls',  namespace='control_panel', app_name='control_panel')),
    url(r'^newsletter/', include('newsletters.urls',  namespace='newsletters', app_name='newsletters')),
    url(r'^tutorials/', include('tutorials.urls',  namespace='tutorials', app_name='tutorials')),
    url(r'^accounts/', include('accounts.urls',  namespace='accounts', app_name='accounts')),
]

tutorials/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^series/(?P<slug>[-\w]+)/$', views.tutorial_series_detail, name="tutorial_series_detail"),
    #url(regex=r'^series/(?P<slug>[-\w]+)/$', view=views.TutorialSeriesDetailView.as_view(), name="tutorial_series_detail"),
    #url(regex=r'^series/(?P<tutorial_series>[-\w]+)/(?P<slug>[-\w]+)/$', view=views.LessonDetailView.as_view(), name="lesson_detail"),
    
    #url(r'^series/$', views.TutorialSeriesListView.as_view(), name="tutorial_series_list_view"),
    url(regex=r'^series/(?P<slug>[-\w]+)/$', view=views.tutorial_series_detail, name="tutorial_series_detail"),
    url(regex=r'^series/(?P<tutorial_series>[-\w]+)/(?P<slug>[-\w]+)/$', view=views.lesson_detail, name="lesson_detail"),
    url(r'^series/$', views.tutorial_series_list, name="tutorial_series_list"),
    
]

tutorials/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.template.defaultfilters import slugify

# Create your models here.
class Language(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(max_length=250, unique=True)
    active = models.BooleanField(default=False)
    
    def save(self, *args, **Kwargs):
        self.slug = slugify(self.name)
        super(Language, self).save(*args, **Kwargs)
        
    def get_absolute_url(self):
        return reverse('tutorials:language', args=[self.slug] )

    def __str__(self):
        return self.name
    
class StudentExperience(models.Model):
    EXPERIENCE_LEVEL_CHOICES = (
        ('Beginner', 'Beginner'),
        ('Intermediate', 'Intermediate'),
        ('Advanced', 'Advanced'),
    )
    
    experience_level = models.CharField(max_length=20, choices=EXPERIENCE_LEVEL_CHOICES, default='Beginner')
    
    def __str__(self):
        return self.experience_level
    
class TutorialSeries(models.Model):
    language = models.ForeignKey(Language)
    student_experience = models.ForeignKey(StudentExperience)
    name = models.CharField(max_length=250)
    description = models.TextField(blank=True, null=True)
    archived = models.BooleanField(default=False)
    slug = models.SlugField(max_length=250, unique=True)
    
    def save(self, *args, **Kwargs):
        self.slug = slugify(self.name)
        super(TutorialSeries, self).save(*args, **Kwargs)
        
    def get_absolute_url(self):
        return reverse('tutorials:tutorial_series_detail', args=[self.slug] )
    
    def __str__(self):
        return self.name
    
class Lesson(models.Model):
    tutorial_series = models.ForeignKey(TutorialSeries, related_name='tutorials')  #Con related name,  podemos ver e numero de lecciones que tiene un tutorial
    title = models.CharField(max_length=250)
    video = models.TextField(blank=True, null=True)
    length = models.CharField(max_length=50, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    slug = models.SlugField(max_length=250, unique=True)
    free_preview = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    
    def save(self, *args, **Kwargs):
        self.slug = slugify(self.title)
        super(Lesson, self).save(*args, **Kwargs)
    
    def get_absolute_url(self):
        return reverse('tutorials:lesson_details', args=[self.slug] )

    def __str__(self):
        return self.title
    
    
    
    
    
    

tutorials/views.py
from django.shortcuts import render, get_object_or_404
#from django.views.generic import DetailView   no es necesario
#from django.views.generic import ListView
from django.db.models import Count
from .models import TutorialSeries, Lesson
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
#def tutorial_series_detail(request, slug):
#    object = get_object_or_404(TutorialSeries, slug=slug)
#    template = "tutorials/tutorialseries_detail.html"
#    context = {
#        'object': object,
#    }
#    return render(request, template, context)
    
    
#class TutorialSeriesDetailView(DetailView):
#    model = TutorialSeries
    
#    def get_context_data(self, **kwargs):
#        context = super(TutorialSeriesDetailView, self).get_context_data(**kwargs)
#        context['lessons'] = Lesson.objects.filter(tutorial_series=self.object)
#        return context
    
#class LessonDetailView(DetailView):
#    model = Lesson
     
#    def get_object(self, tutorial_series, slug):
#        tutorial_series = TutorialSeries.objects.filter(slug=tutorial_series).first()
#        object = get_object_or_404(Lesson, tutorial_series=tutorial_series, slug=slug)
#        return object
    
#    def get(self, request, tutorial_series, slug):
#        self.object = self.get_object(tutorial_series, slug)
#        context = self.get_context_data(object=self.object)
#        return self.render_to_response(context)

#class TutorialSeriesListView(ListView):
#    model = TutorialSeries

def tutorial_series_list(request):
    tutorials = TutorialSeries.objects.all().prefetch_related(
        'tutorials'
    ).annotate(
        lesson=Count('tutorials')
    )               # Con esto podemos ver e numero de lecciones que tiene un tutorial 
    
    paginator = Paginator(tutorials, 2)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
        
    index = items.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 5 if index >= 5 else 0
    end_index = index + 5 if index <= max_index - 5 else max_index 
    page_range = paginator.page_range[start_index:end_index]
    
    template = "tutorials/tutorialseries_list.html"
    context = {
        'tutorials': tutorials,
        'items': items,
        'page_range': page_range,
    }
    return render(request, template, context)
    

def tutorial_series_detail(request, slug):
    series = get_object_or_404(TutorialSeries, slug=slug)
    lessons = series.tutorials.filter(tutorial_series=series)
    
    template = "tutorials/tutorialseries_detail.html"
    
    context = {
        'series': series,
        'lessons': lessons,
    }
    return render(request, template, context)


def lesson_detail(request, tutorial_series, slug):
    item = get_object_or_404(Lesson.objects.filter(tutorial_series__slug=tutorial_series, slug=slug))
    template = "tutorials/lesson_detail.html"
    context = {
        'item': item,
    }
    
    return render(request, template, context)

templates/tutorials/lesson_detail.html
{% extends 'base.html' %}

{% block content %}
	
	
	<div class="embed-responsive embed-responsive-16by9">
		<iframe class="embed-responsive-item" src="{{item.video}}"></iframe>
	</div>
	
	<div class="container">
		<div class="row">
			<div class="page-header">
				<h1>{{ item.title }}</h1>
			</div>
		</div>
		<div class="row">
			{{ item.content }}
		</div>
	</div>
{% endblock %} 

templates/tutorials/tutorialseries_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
      <div class="container">
        <h1>{{ series.name }}</h1>
        <p>{{ series.description }}</p>
        <p>Experience Level: {{ series.student_experience }}</p>
      </div>
    </div>
    <div class="container">
	    	<ul class="list-group">
			{% for lesson in lessons %}
			<li class="list-group-item">
				<span class="badge">{{ lesson.length }}</span>
				<a href="{% url 'tutorials:lesson_detail' lesson.tutorial_series.slug lesson.slug %}">{{ lesson.title }}</a>
			</li>
			{% endfor %}
		</ul>
	</div>
{% endblock %} 

templates/tutorials/tutorialseries_list.html
{% extends 'base.html' %}  

{% block content %}
<div class="container">
	{% for item in items %}
		{% if forloop.counter|divisibleby:2 %}
		      <div class="row featurette">
		        <div class="col-md-7">
		          <h2 class="featurette-heading"><a href="{% url 'tutorials:tutorial_series_detail' item.slug %}">{{item.name}}</a> <span class="text-muted">{{item.lesson}} Tutorials</span></h2>
		          <p><strong>Student Experience: {{item.student_experience}}</strong></p>
		          <p class="lead">{{item.description|truncatechars:250}}</p>
		        </div>
		        <div class="col-md-5">
		          	<div class="embed-responsive embed-responsive-16by9">
						<iframe class="embed-responsive-item" src="{{item.tutorials.all.0.video}}"></iframe>
					</div>
		        </div>
		      </div>
		
		{% else %}
		      <hr class="featurette-divider">
		
		      <div class="row featurette">
		        <div class="col-md-7 col-md-push-5">
		          <h2 class="featurette-heading"><a href="{% url 'tutorials:tutorial_series_detail' item.slug %}">{{item.name}}</a> <span class="text-muted">{{item.lesson}} Tutorials</span></h2>
		          <p><strong>Student Experience: {{item.student_experience}}</strong></p>
		          <p class="lead">{{item.description|truncatechars:250}}</p>
		        </div>
		        <div class="col-md-5 col-md-pull-7">
		          	<div class="embed-responsive embed-responsive-16by9">
						<iframe class="embed-responsive-item" src="{{item.tutorials.all.0.video}}"></iframe>
					</div>
		        </div>
		      </div>
		
		{% endif %}
	{% endfor %}
	{% include "pagination.html" %}
</div>
{% endblock %} 