accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib import admin

from . import views as core_views

urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'accounts:login'}, name='logout'),
    
    url(r'^signup/$', core_views.signup, name='signup'),
    
    url(r'^account_activation_sent/$', core_views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),

]

# https://simpleisbetterthancomplex.com/tutorial/2017/02/18/how-to-create-user-sign-up-view.html

control_panel/urls.py
from django.conf.urls import url
from newsletters.views import control_newsletter, control_newsletter_list, control_newsletter_detail, control_newsletter_edit, control_newsletter_delete

urlpatterns = [
    url(r'^newsletter/$', control_newsletter, name='control_newsletter'),
    url(r'^newsletter-list/$', control_newsletter_list, name='control_newsletter_list'),
    url(r'^newsletter-detail/(?P<pk>\d+)/$', control_newsletter_detail, name='control_newsletter_detail'),
    url(r'^newsletter-edit/(?P<pk>\d+)/$', control_newsletter_edit, name='control_newsletter_edit'),
    url(r'^newsletter-delete/(?P<pk>\d+)/$', control_newsletter_delete, name='control_newsletter_delete'),
]

master/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home, name='home'),
    url(r'^control/', include('control_panel.urls',  namespace='control_panel', app_name='control_panel')),
    url(r'^newsletter/', include('newsletters.urls',  namespace='newsletters', app_name='newsletters')),
    url(r'^tutorials/', include('tutorials.urls',  namespace='tutorials', app_name='tutorials')),
    url(r'^accounts/', include('accounts.urls',  namespace='accounts', app_name='accounts')),
]

tutorials/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^series/(?P<slug>[-\w]+)/$', views.tutorial_series_detail, name="tutorial_series_detail"),
    #url(regex=r'^series/(?P<slug>[-\w]+)/$', view=views.TutorialSeriesDetailView.as_view(), name="tutorial_series_detail"),
    #url(regex=r'^series/(?P<tutorial_series>[-\w]+)/(?P<slug>[-\w]+)/$', view=views.LessonDetailView.as_view(), name="lesson_detail"),
    
    #url(r'^series/$', views.TutorialSeriesListView.as_view(), name="tutorial_series_list_view"),
    url(regex=r'^series/(?P<slug>[-\w]+)/$', view=views.tutorial_series_detail, name="tutorial_series_detail"),
    url(regex=r'^series/(?P<tutorial_series>[-\w]+)/(?P<slug>[-\w]+)/$', view=views.lesson_detail, name="lesson_detail"),
    url(r'^series/$', views.tutorial_series_list, name="tutorial_series_list"),
    
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Jumbotron Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/jumbotron.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static 'js/ie8-responsive-file-warning.js' %}"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button> 
          <a class="navbar-brand" href="{% url 'home' %}">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        		{% with url_name=request.resolver_match.url_name %}
        		<ul class="nav navbar-nav">
        			<li class="{% if url_name == 'home' %}active {% endif %}"><a href="{% url 'home' %}">Home</a></li>
        			<li class="{% if url_name == 'tutorial_series_list' %}active {% endif %}"><a href="{% url 'tutorials:tutorial_series_list' %}">Tutorials</a></li>
        			{% if user.is_authenticated %}
        			<li class="{% if url_name == 'logout' %}active {% endif %}"><a href="{% url 'accounts:logout' %}">Logout</a></li>
        			{% else %}
        			<li class="{% if url_name == 'login' %}active {% endif %}"><a href="{% url 'accounts:login' %}">Login</a></li>
        			<li class="{% if url_name == 'signup' %}active {% endif %}"><a href="{% url 'accounts:signup' %}">Signup</a></li>
        			{% endif %}
        		</ul>
        		{% endwith %}
	          <form class="navbar-form navbar-right">
	            <div class="form-group">
	              <input type="text" placeholder="Email" class="form-control">
	            </div>
	            <div class="form-group">
	              <input type="password" placeholder="Password" class="form-control">
	            </div>
	            <button type="submit" class="btn btn-success">Sign in</button>
	          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

	{% block content %}
    
	{% endblock %}
      <hr>

      <footer>
        <p>&copy; 2016 Company, Inc.</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

templates/control_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="{% static 'js/ie8-responsive-file-warning.js' %}"></script><![endif]-->
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{% url 'control_panel:control_newsletter' %}">Newsletter</a></li>
            <li><a href="{% url 'control_panel:control_newsletter_list' %}">Newsletter list</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	        {% block content %}
	    
			{% endblock %}
			
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}
<!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
      	{% for item in series %}
        <div class="col-md-4 text-center">
          <h2>{{item.name}}</h2>
          <p>{{item.description|truncatechars:100}}</p>
          <p><a class="btn btn-default" href='{% url "tutorials:tutorial_series_detail" item.slug %}' role="button">View details &raquo;</a></p>
        </div>
        {% endfor %}
      </div>
{% endblock %}

templates/pagination.html
{% if items.has_other_pages %}
	<div class="col-6 offset-3 text-center paginator-set">
		<nav aria-label="">
			<ul class="pagination">
				{% if items.has_previous %}
					<li class="page-item"><a class="page-link" aria-label="Previous" href="?page={{items.previous_page_number}}"> << </a></li>
				{% else %}	
					<li class="page-item disabled"><a class="page-link"><span> << </span></a></li>
				{% endif %}
				{% for i in page_range %}
					{% if items.number == i %}
						<li class="page-item active"><a class="page-link" href="">{{i}}<span class="sr-only">(current)</span></a></li>
					{% else %}
						<li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
					{% endif %}
				{% endfor %}
				{% if items.has_next %}
					<li class="page-item"><a class="page-link" aria-label="Next" href="?page={{items.next_page_number}}">>></a></li>
				{% else %}	
					<li class="page-item disabled "><a class="page-link"><span>>></span></a></li>
				{% endif %}
			</ul>
		</nav>
	</div>
{% endif %}